### ISSUE TITLE
Update version of HttpAsyncClient. Now it uses 4.0-beta3.

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee.http#10]
If I change only version to 4.0 in parent pom.xml I have errors:

> [ERROR] /home/sergeypovarnin/Projects/MobiusRepo/jain-slee.http/resources/http-client-nio/ra/src/main/java/org/mobicents/slee/ra/httpclient/nio/ra/HttpClientNIOResourceAdaptor.java:[123,22] error: cannot find symbol
> [ERROR] variable httpclient of type HttpAsyncClient
> /home/sergeypovarnin/Projects/MobiusRepo/jain-slee.http/resources/http-client-nio/ra/src/main/java/org/mobicents/slee/ra/httpclient/nio/ra/HttpClientNIOResourceAdaptor.java:[153,27] error: cannot find symbol
> [ERROR] variable httpclient of type HttpAsyncClient
> /home/sergeypovarnin/Projects/MobiusRepo/jain-slee.http/resources/http-client-nio/ra/src/main/java/org/mobicents/slee/ra/httpclient/nio/ra/HttpClientNIOResourceAdaptorSbbInterfaceImpl.java:[41,22] error: cannot find symbol
> [INFO] 3 errors

Perhaps we can update HttpAsyncClient to last 4.1.x version.

**Comment by yarel79** [comment]
What is the purpose of exposing parameters used to initialize HttpClient ? 

https://github.com/RestComm/jain-slee.http/blob/master/resources/http-client-nio/ratype/src/main/java/org/mobicents/slee/ra/httpclient/nio/ratype/HttpClientNIOResourceAdaptorSbbInterface.java#L49

HttpParams are deprecated as of version 4.3:
https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/params/HttpParams.html

Shouldn't upgrading HttpAsyncClient also consider getting rid of HttpParams info from RA interface?

**Comment by jaimecasero** [comment]
If the idea is to upgrade up to version4.3, then we should really consider replacing getHttpClientParams. See that I mentioned "replacement" over "removal",since we should still support the same functionality. 

This kind of API modification is tough since we need to consider the migration effort of an existing SBB wanting to port to the new API...

**Comment by deruelle** [comment]
@jaimecasero agreed. Except if we do this as part of a new major version of JAIN SLEE in which case it is assumed some backward compatibility will be broken.

**Comment by yarel79** [comment]
Actually I haven't seen any reference to getHttpClientParams(), therefore curious why this method is exposed at all. 

Since RA has its configuration, then I would expect that the configuration is known to a party who initializes the adapter instance. Once the adapter is up and running, then who would need to get configuration parameters of the managed http client connection(s)? 

Seems like upgrading to HttpClient < 4.3 shouldn't break interface copatibility.

**Comment by jaimecasero** [comment]
"Actually I haven't seen any reference to getHttpClientParams(), therefore curious why this method is exposed at all. " -> I was thinking the same first time I saw it, but who knows how final services/SBB are using that to complete their logics. 

Can we consider that a readOnly method? I mean, if an SBB gets the params, and set some parameter, will that affect to subsequent HTTP requests? Apparently we can from doc "Once initialized, HTTP parameters are not expected to mutate in the course of HTTP message processing" . In that case, replacing/removing will be a lowRisk decision.

**Comment by yarel79** [comment]
I'll try to provide PR with HttpClient < 4.3, not to mess with API compatiblity issues.

On the other hand It would be interesting to observe process of upgrading RA version, from something like:
`<resource-adaptor-type-name>HttpClientNIO</resource-adaptor-type-name>
        <resource-adaptor-type-vendor>org.mobicents</resource-adaptor-type-vendor>
        <resource-adaptor-type-version>1.0</resource-adaptor-type-version>
`, to e.g. 1.1. Just to see how it is handled ;) 

Possible future solution could be like: 
- mark in the interface getHttpClientParams() as deprecated
- enhance the interface with operation getRequestConfig();  (org.apache.http.client.config.RequestConfig) 
- provide some kind of a mapping/wrapper between RequestConfig and HttpParams for backward compatibility
- possibly enhance RA resource-adaptor-jar.xml with broader set of tunable HTTP Client parameters 
  (or to leave users with JVM -Dswitches=... )

**Comment by deruelle** [comment]
@yarel79 this sounds like a good plan to me. 
If there is backward incompatible changes the version should actually be bumped to 2.0 and not 1.1.= so users know to expect changes.

**Comment by deruelle** [comment]
@yarel79 were you able to work out and implement a solution for this ?

**Comment by yarel79** [comment]
I did some analysis considering present situation of HTTP Client NIO with regards to librariaes used:
- httpasynclient-4.0-beta3
- httpcore (4.2.2)

Seems that:

a) HttpAsyncClient interface (of httpasynclient-4.0-beta3) is deprecated as of 4.0-beta4 with regards to the following operations:

- start()
- shutdown()
- getStatus()
- getConnectionManager()
- getParams() 

b) httpasynclient-4.0 (i.e. next after 4.0-beta*) has these operations no longer provided in HttpAsyncClient interface

c) HttpParams (of httpcore-4.2.2) is NOT deprecated 
d) HttpParams gets deprecated as of httpcore-4.3

Now, if we need to maintain present RA interface, that means, at most 4.0-beta4 can be used, which appears to be pointless from the upgrade perspective.

At some point compatibility break will be a must, so why not to do it now?

**Comment by deruelle** [comment]
@yarel79 it seems fine to do so but we should make sure to comply to https://github.com/RestComm/jain-slee.http/issues/10#issuecomment-256936833

**Comment by SergeyLee** [comment]
@yarel79 @deruelle so I can add new branch for developing http-client-nio with last HttpAsyncClient and HttpCore.
@yarel79 did you have pull requests?

**Comment by yarel79** [comment]
@SergeyLee, @deruelle: PR has been created: https://github.com/RestComm/jain-slee.http/pull/12 for existing master branch.  Not sure whether this is the best approach. 

Possibly dedicated branch for 2.0 should be created and PR merged there?  This is a concern (i.e. bump of RA version) which as well may appear in the future , and would be good to have it described, e.g. in "TeleStax Open Source Playbook".

**Comment by SergeyLee** [comment]
I will create branch for old (1.0) version and master branch will be for new (2.0) version. Also I will fix CloudBees CI job for building old version.

**Comment by SergeyLee** [comment]
@yarel79 I merged your PR. Please try to test new http-client-nio in your app. And if it works well then we can close this issue.
