### ISSUE TITLE
Documentation update - empty HTTP response event processing description

### ISSUE THREAD

**Issue by tzieleniewski** [RestComm/jain-slee.http#7]
When there is an IOException during the HTTP method execution, RA fires an empty HTTP Response Event, where HTTP response object is null. Situation applies both in HTTP Client RA and HTTP Client NIO RA.

Such situation, if not processed correctly, leads to runtime NPE exception.
SBBs, during response event processing, should first call ResponseEvent#getException method and only if that gives back null then they should call ResponseEvent#getHttpResponse.

**Comment by tzieleniewski** [comment]
Pull request created: https://github.com/RestComm/jain-slee.http/pull/8

**Comment by deruelle** [comment]
@SergeyLee please review

**Comment by SergeyLee** [comment]
Ok, I reviewed issue and pull request. I splited your commit into 2 commits: refactorizing Maven pom.xml files and updating documentation.
