### ISSUE TITLE
HTTP Servlet RA - default HTTP response status change

### ISSUE THREAD

**Issue by tzieleniewski** [RestComm/jain-slee.http#9]
Hi,

Currenty if there is no HTTP servlet request processing invoked within SBB, the default 200 OK response is returned. Such response status appears to be missleading as in fact, there is no request processing on the server side.

The [501 Not Implemented](https://tools.ietf.org/html/rfc2616#section-10.5.2) response seems to be the most proper indication for the client side.

I propose to introduce such modification.

Godspeed
Tomasz Krzysztof Zieleniewski

**Comment by SergeyLee** [comment]
Hi Tomasz!
I reviewed your issue and commit from pull request and merged them to master branch.
Please read more about this in pull request comments.
